name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    paths-ignore: "**/README.md"
    # # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'
      
permissions:
    contents: write
    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      libraryName: crosstool-ng
      tagName: crosstool-ng-1.28.0
    steps:
    
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Build
        run: |
          echo "Free space:"
          df -h
          
      - uses: actions/checkout@v4
        with:
          repository: crosstool-ng/crosstool-ng
          path: ${{ env.libraryName }}
          ref: ${{ env.tagName }}
          submodules: true

      - shell: bash
        run: |
          sudo apt-get update && \
          sudo apt-get install -y gcc g++ gperf bison flex texinfo help2man make libncurses5-dev \
              python3-dev autoconf automake libtool libtool-bin gawk wget bzip2 xz-utils unzip \
              patch libstdc++6 rsync git meson ninja-build

      - shell: bash
        run: |
          sudo apt-get clean && \
          sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
          
              
      - shell: bash
        working-directory: ${{ env.libraryName }}
        run: |
          export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" && \
          ./bootstrap && \
          ./configure --help && \
          ./configure --enable-local && \
          make
      # make install is omitted because --enable-local is used

  # ct-ng menuconfig
      - shell: bash
        working-directory: ${{ env.libraryName }}
        run: |
          ./ct-ng list-samples
          
      - shell: bash
        working-directory: ${{ env.libraryName }}
        run: |
          ./ct-ng arm-none-eabi

      - shell: bash
        working-directory: ${{ env.libraryName }}
        run: |
          ./ct-ng build
          
      - shell: bash
        working-directory: ${{ env.libraryName }}
        run: |
          ls -R
